"""new update

Revision ID: 778d637f5ca9
Revises: 47e59a5b6d38
Create Date: 2021-09-10 23:29:25.201187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '778d637f5ca9'
down_revision = '47e59a5b6d38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cuisine_name_key', 'cuisine', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('cuisine_name_key', 'cuisine', ['name'])
    # ### end Alembic commands ###
